### ISSUE TITLE
sass command working fine in root user but normal user not working proper

### ISSUE THREAD

**Issue by devendraram** [sass/dart-sass#1278]
os : centos 7
node : v15.4.0

[newshoppr@e2e-71-254 home]$ sass
/usr/lib/node_modules/sass/node_modules/chokidar/index.js:161
  async remove(item) {
        ^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/sass/sass.dart.js:116:17)

**Comment by nex3** [comment]
I'm guessing that your root account and your user account are using different versions of Node. Note that all odd-numbered Node versions, including Node 15.x, are effectively beta versions and are frequently unsupported. In this case, I believe Chokidar doesn't support Node 15.
