### ISSUE TITLE
dartException: Bad state: Can't access __parent outside of a module

### ISSUE THREAD

**Issue by Vovan-VE** [sass/dart-sass#1318]
Hello!

I'm trying to migrate a project with help of `sass-migrator module`. After migration I fixed some syntax/logic errors, the sass  crashed with the exception, provided below. Probably, it could mean, that I did fix all of obvious errors.

I have 132 *.scss files in the project, and almost all of reported errors I did fix with search/replace in IDE. I have completely no ideas, which files cause the crash. Currently I have no idea how to find the source of crash easily.

software | version
--- | ---
sass | 1.33.0 compiled with dart2js 2.13.0
node | 14.16.0
npm | 7.12.1
react-scripts (CRA) | 4.0.3

```
/REPO/node_modules/sass/sass.dart.js:27218
      throw error;
      ^

Bad state: Can't access __parent outside of a module.
    at Object.wrapException (/REPO/node_modules/sass/sass.dart.js:1231:17)
    at _EvaluateVisitor2._async_evaluate0$_assertInModule$1$2 (/REPO/node_modules/sass/sass.dart.js:64286:15)
    at _EvaluateVisitor2._async_evaluate0$_assertInModule$2 (/REPO/node_modules/sass/sass.dart.js:64289:19)
    at /REPO/node_modules/sass/sass.dart.js:67425:27
    at _wrapJsFunctionForAsync_closure.$protected (/REPO/node_modules/sass/sass.dart.js:4365:15)
    at _wrapJsFunctionForAsync_closure.call$2 (/REPO/node_modules/sass/sass.dart.js:25699:12)
    at Object._asyncStartSync (/REPO/node_modules/sass/sass.dart.js:4329:20)
    at _EvaluateVisitor2.visitCssDeclaration$body$_EvaluateVisitor0 (/REPO/node_modules/sass/sass.dart.js:67430:16)
    at _EvaluateVisitor2.visitCssDeclaration$1 (/REPO/node_modules/sass/sass.dart.js:67411:19)
    at ModifiableCssDeclaration0.accept$1$1 (/REPO/node_modules/sass/sass.dart.js:73356:22)
    at ModifiableCssDeclaration0.accept$1 (/REPO/node_modules/sass/sass.dart.js:73359:19)
    at /REPO/node_modules/sass/sass.dart.js:71166:67
    at _wrapJsFunctionForAsync_closure.$protected (/REPO/node_modules/sass/sass.dart.js:4365:15)
    at _wrapJsFunctionForAsync_closure.call$2 (/REPO/node_modules/sass/sass.dart.js:25699:12)
    at _awaitOnObject_closure.call$1 (/REPO/node_modules/sass/sass.dart.js:25685:32)
    at Object._rootRunUnary (/REPO/node_modules/sass/sass.dart.js:4740:18) {
  dartException: <ref *1> StateError {
    message: "Can't access __parent outside of a module.",
    '$thrownJsError': <ref *2> Bad state: Can't access __parent outside of a module.
        at Object.wrapException (/REPO/node_modules/sass/sass.dart.js:1231:17)
        at _EvaluateVisitor2._async_evaluate0$_assertInModule$1$2 (/REPO/node_modules/sass/sass.dart.js:64286:15)
        at _EvaluateVisitor2._async_evaluate0$_assertInModule$2 (/REPO/node_modules/sass/sass.dart.js:64289:19)
        at /REPO/node_modules/sass/sass.dart.js:67425:27
        at _wrapJsFunctionForAsync_closure.$protected (/REPO/node_modules/sass/sass.dart.js:4365:15)
        at _wrapJsFunctionForAsync_closure.call$2 (/REPO/node_modules/sass/sass.dart.js:25699:12)
        at Object._asyncStartSync (/REPO/node_modules/sass/sass.dart.js:4329:20)
        at _EvaluateVisitor2.visitCssDeclaration$body$_EvaluateVisitor0 (/REPO/node_modules/sass/sass.dart.js:67430:16)
        at _EvaluateVisitor2.visitCssDeclaration$1 (/REPO/node_modules/sass/sass.dart.js:67411:19)
        at ModifiableCssDeclaration0.accept$1$1 (/REPO/node_modules/sass/sass.dart.js:73356:22)
        at ModifiableCssDeclaration0.accept$1 (/REPO/node_modules/sass/sass.dart.js:73359:19)
        at /REPO/node_modules/sass/sass.dart.js:71166:67
        at _wrapJsFunctionForAsync_closure.$protected (/REPO/node_modules/sass/sass.dart.js:4365:15)
        at _wrapJsFunctionForAsync_closure.call$2 (/REPO/node_modules/sass/sass.dart.js:25699:12)
        at _awaitOnObject_closure.call$1 (/REPO/node_modules/sass/sass.dart.js:25685:32)
        at Object._rootRunUnary (/REPO/node_modules/sass/sass.dart.js:4740:18) {
      dartException: [Circular *1],
      '$cachedTrace': _StackTrace {
        _exception: [Circular *2],
        _trace: "Bad state: Can't access __parent outside of a module.\n" +
          '    at Object.wrapException (/REPO/node_modules/sass/sass.dart.js:1231:17)\n' +
          '    at _EvaluateVisitor2._async_evaluate0$_assertInModule$1$2 (/REPO/node_modules/sass/sass.dart.js:64286:15)\n' +
          '    at _EvaluateVisitor2._async_evaluate0$_assertInModule$2 (/REPO/node_modules/sass/sass.dart.js:64289:19)\n' +
          '    at /REPO/node_modules/sass/sass.dart.js:67425:27\n' +
          '    at _wrapJsFunctionForAsync_closure.$protected (/REPO/node_modules/sass/sass.dart.js:4365:15)\n' +
          '    at _wrapJsFunctionForAsync_closure.call$2 (/REPO/node_modules/sass/sass.dart.js:25699:12)\n' +
          '    at Object._asyncStartSync (/REPO/node_modules/sass/sass.dart.js:4329:20)\n' +
          '    at _EvaluateVisitor2.visitCssDeclaration$body$_EvaluateVisitor0 (/REPO/node_modules/sass/sass.dart.js:67430:16)\n' +
          '    at _EvaluateVisitor2.visitCssDeclaration$1 (/REPO/node_modules/sass/sass.dart.js:67411:19)\n' +
          '    at ModifiableCssDeclaration0.accept$1$1 (/REPO/node_modules/sass/sass.dart.js:73356:22)\n' +
          '    at ModifiableCssDeclaration0.accept$1 (/REPO/node_modules/sass/sass.dart.js:73359:19)\n' +
          '    at /REPO/node_modules/sass/sass.dart.js:71166:67\n' +
          '    at _wrapJsFunctionForAsync_closure.$protected (/REPO/node_modules/sass/sass.dart.js:4365:15)\n' +
          '    at _wrapJsFunctionForAsync_closure.call$2 (/REPO/node_modules/sass/sass.dart.js:25699:12)\n' +
          '    at _awaitOnObject_closure.call$1 (/REPO/node_modules/sass/sass.dart.js:25685:32)\n' +
          '    at Object._rootRunUnary (/REPO/node_modules/sass/sass.dart.js:4740:18)'
      }
    }
  }
}
```

**Comment by nex3** [comment]
This is definitely a bug! But in order to fix it, I'll need to figure out howto reproduce it. A good place to start is by binary searching: First, delete half of the `.scss` files in your app, and see if the bug still appears. If it does, you know the bug was caused by one of the files that remains; if it doesn't, you know it was caused by one of the files you deleted. Either way, keep the half that contained the bug, then repeat the process. Eventually you'll narrow down your files to one or two that consistently reproduce the issue.

**Comment by Vovan-VE** [comment]
I did reproduce the crash in fresh CRA installation: https://github.com/Vovan-VE/sass-issue-1318
A problematic files are located in [`src/styles/`](https://github.com/Vovan-VE/sass-issue-1318/tree/master/src/styles).

Running `npm start` or `npm run build` both cause the same crash. I also tried codesandbox.io, but it works is some different way.

However `npx sass src/styles/index.scss` does NOT crash.

**Comment by Vovan-VE** [comment]
In fact, it's not the only case for the same crash. I hope this one case is enough to reproduce the crash.

**Comment by Vovan-VE** [comment]
sass 1.32.8 - OK
sass 1.32.9 - crash

**Comment by nex3** [comment]
I can't reproduce the error in that repo; `npm run build` completes successfully for me.

**Comment by Vovan-VE** [comment]
https://www.travis-ci.com/github/Vovan-VE/sass-issue-1318

**Comment by nex3** [comment]
Without a way to reproduce this locally, it's going to be extremely difficult for me to debug it.

**Comment by Vovan-VE** [comment]
I wished to `npm i` a specific revision from source between `1.32.8` and `1.32.9` to find specific commit in which the crash was introduced. But it's not possible out of the box, since sass repo has no dist code. I'm not familiar with Dart and I cannot see instructions how to build sass from source for that.

When you said you cannot reproduce the issue, I though it would be OS specific. But issue was reproduced with Travis on all of 3 major OSs. Now I really woundered how it works for you without a crash.

**Comment by Vovan-VE** [comment]
CI by a link above was restarted with 3 different Node versions and all of them crashed.

**Comment by nex3** [comment]
It's not that I don't believe the issue exists. It's that I can't really do anything about it if I can't debug into the code and figure out why it's happening.

**Comment by ghost91-** [comment]
I am having the exact same problem and I can also confirm that the problem was introduced in v1.32.9. v1.32.8 is still OK (and is what I have been using for quite some time). Interestingly enough, it only happens when invoking sass via gulp (happens with both `gulp-sass` and `gulp-dart-sass`). directly compiling with `yarn sass ...` works just fine. I'll try to create a minimal example.

**Comment by nex3** [comment]
We're backed up on bugs right now, but I'll assign someone to look at this next week.
