### ISSUE TITLE
node-pre-gyp WARN Hit error connect ECONNREFUSED 51.75.72.12:443                                                      

### ISSUE THREAD

**Issue by Marietto2008** [sass/dart-sass#1386]
Hello to everyone. I would like to install ferdi inside docker on my jetson nano (arm64). Below u can see what I did right now. Unfortunately there is an error I'm not able to fix.

**FROM ubuntu:hirsute
LABEL Title="arm64/ferdi"

Enviorment variables

ARG username=mario
ENV HOME /home/$blenderartistusername
ENV DEBIAN_FRONTEND noninteractive
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
ENV PATH "/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/lib:/usr/include:/usr/share"
ENV HW="GPU"
ENV ELECTRON_CACHE /home/$username/.cache/electron
ENV ELECTRON_BUILDER_CACHE /home/$username/.cache/electron-builder
ENV TERM xterm

RUN mkdir /home/$username

#RUN apt-get update && apt-get install -y build-essential clang libdbus-1-dev libgtk-3-dev libnotify-dev libgnome-keyring-dev libasound2-dev libcap-dev libcups2-dev libxtst-dev libxss1 libnss3-dev gcc-multilib g++-multilib curl gperf bison python-dbusmock openjdk-8-jre libc6-dev-arm64-cross linux-libc-dev-arm64-cross g++-aarch64-linux-gnu

RUN apt-get update && apt-get install -y ca-certificates curl netbase wget tzdata rpm git xz-utils nano gedit

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -

RUN apt-get install -y nodejs gcc g++ make

RUN curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | tee /usr/share/keyrings/yarnkey.gpg >/dev/null

RUN echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update && apt-get install yarn

RUN git clone https://github.com/getferdi/ferdi.git && cd ferdi && git submodule update --init --recursive

Note: This is being set to bypass the error with missing git repo information for the 'preval-build-info' module

ENV PREVAL_BUILD_INFO_PLACEHOLDERS=true

WORKDIR /ferdi

RUN npx lerna init 
RUN npm install --save-dev sass**

This is the error :

```
Step 27/29 : RUN npx lerna init
 ---> Using cache
 ---> 7f03a8b3a311
Step 28/29 : RUN npm install --save-dev sass
 ---> Running in 9a4046749215

> macos-notification-state@1.3.5 install /ferdi/node_modules/macos-notification-state
> node-gyp rebuild

make: Entering directory '/ferdi/node_modules/macos-notification-state/build'
  CXX(target) Release/obj.target/notificationstate/lib/notificationstate.o
../lib/notificationstate.cc:40:19: warning: ‘napi_value__* GetDoNotDisturb(napi_env, napi_callback_info)’ defined but not used [-Wunused-function]                                                                                          
   40 | static napi_value GetDoNotDisturb(napi_env env, napi_callback_info info) {                                    
      |                   ^~~~~~~~~~~~~~~                                                                             
../lib/notificationstate.cc:28:19: warning: ‘napi_value__* QueryUserSessionState(napi_env, napi_callback_info)’ defined but not used [-Wunused-function]                                                                                    
   28 | static napi_value QueryUserSessionState(napi_env env, napi_callback_info info) {                              
      |                   ^~~~~~~~~~~~~~~~~~~~~                                                                       
  SOLINK_MODULE(target) Release/obj.target/notificationstate.node
  COPY Release/notificationstate.node
make: Leaving directory '/ferdi/node_modules/macos-notification-state/build'

> abstract-socket@2.1.1 install /ferdi/node_modules/abstract-socket
> node-gyp rebuild

make: Entering directory '/ferdi/node_modules/abstract-socket/build'
  CXX(target) Release/obj.target/bindings/src/abstract_socket.o
In file included from ../../nan/nan.h:56,
                 from ../src/abstract_socket.cc:5:                                                                    
/home/.cache/node-gyp/14.17.2/include/node/node.h:758:7: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]                                                                                      
  758 |       (node::addon_register_func) (regfunc),                          \                                       
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                   
/home/.cache/node-gyp/14.17.2/include/node/node.h:792:3: note: in expansion of macro ‘NODE_MODULE_X’                  
  792 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)                                
      |   ^~~~~~~~~~~~~                                                                                               
../src/abstract_socket.cc:181:1: note: in expansion of macro ‘NODE_MODULE’                                            
  181 | NODE_MODULE(abstract_socket, Initialize)                                                                      
      | ^~~~~~~~~~~                                                                                                   
  SOLINK_MODULE(target) Release/obj.target/bindings.node
  COPY Release/bindings.node
make: Leaving directory '/ferdi/node_modules/abstract-socket/build'

> windows-notification-state@1.3.4 install /ferdi/node_modules/windows-notification-state
> node-gyp rebuild

make: Entering directory '/ferdi/node_modules/windows-notification-state/build'
  SOLINK_MODULE(target) Release/obj.target/notificationstate.node
  COPY Release/notificationstate.node
make: Leaving directory '/ferdi/node_modules/windows-notification-state/build'

> windows-quiet-hours@1.2.7 install /ferdi/node_modules/windows-quiet-hours
> node-gyp rebuild

make: Entering directory '/ferdi/node_modules/windows-quiet-hours/build'
  SOLINK_MODULE(target) Release/obj.target/quiethours.node
  COPY Release/quiethours.node
make: Leaving directory '/ferdi/node_modules/windows-quiet-hours/build'

> node-sass@4.14.1 install /ferdi/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/linux-arm64-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.14.1/linux-arm64-83_binding.node": 

HTTP error 404 Not Found                                                                                              

Hint: If github.com is not accessible in your location                                                                
      try setting a proxy via HTTP_PROXY, e.g.                                                                        

      export HTTP_PROXY=http://example.com:1234                                                                       

or configure npm proxy via                                                                                            

      npm config set proxy http://example.com:8080                                                                    

> lzma-native@6.0.1 install /ferdi/node_modules/lzma-native
> node-pre-gyp install --fallback-to-build && rimraf build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for lzma-native@6.0.1 and node@14.17.2 (node-v83 ABI, glibc) (falling back to source compile with node-gyp)                                                                            
node-pre-gyp WARN Hit error connect ECONNREFUSED 51.75.72.12:443                                                      
gyp: Call to 'sh liblzma-config.sh "/ferdi/node_modules/lzma-native/build" "/ferdi/node_modules/lzma-native/deps/xz-5.2.3.tar.bz2"' returned exit status 2 while in binding.gyp. while trying to load binding.gyp                           
gyp ERR! configure error                                                                                              
gyp ERR! stack Error: `gyp` failed with exit code: 1                                                                  
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16) 
gyp ERR! stack     at ChildProcess.emit (events.js:375:28)                                                            
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)                          
gyp ERR! System Linux 4.9.201+                                                                                        
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/ferdi/node_modules/lzma-native/binding-v6.0.1-n-api-linux-arm64/lzma_native.node" "--module_name=lzma_native" "--module_path=/ferdi/node_modules/lzma-native/binding-v6.0.1-n-api-linux-arm64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"                                          
gyp ERR! cwd /ferdi/node_modules/lzma-native                                                                          
gyp ERR! node -v v14.17.2                                                                                             
gyp ERR! node-gyp -v v5.1.0                                                                                           
gyp ERR! not ok                                                                                                       
node-pre-gyp ERR! build error                                                                                         
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/ferdi/node_modules/lzma-native/binding-v6.0.1-n-api-linux-arm64/lzma_native.node --module_name=lzma_native --module_path=/ferdi/node_modules/lzma-native/binding-v6.0.1-n-api-linux-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)                          
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/ferdi/node_modules/node-pre-gyp/lib/util/compile.js:83:29)  
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:375:28)                                                   
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)                                         
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)                  
node-pre-gyp ERR! System Linux 4.9.201+                                                                               
node-pre-gyp ERR! command "/usr/bin/node" "/ferdi/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"     
node-pre-gyp ERR! cwd /ferdi/node_modules/lzma-native                                                                 
node-pre-gyp ERR! node -v v14.17.2                                                                                    
node-pre-gyp ERR! node-pre-gyp -v v0.11.0                                                                             
node-pre-gyp ERR! not ok                                                                                              
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/ferdi/node_modules/lzma-native/binding-v6.0.1-n-api-linux-arm64/lzma_native.node --module_name=lzma_native --module_path=/ferdi/node_modules/lzma-native/binding-v6.0.1-n-api-linux-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/sass/node_modules/chokidar/node_modules/fsevents):                                                                                                            
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})                                                                         
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/@babel/cli/node_modules/fsevents):       
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dmg-license@1.0.9 (node_modules/dmg-license):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for dmg-license@1.0.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/mocha/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lzma-native@6.0.1 install: `node-pre-gyp install --fallback-to-build && rimraf build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lzma-native@6.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2021-07-01T23_33_00_883Z-debug.log
The command '/bin/sh -c npm install --save-dev sass' returned a non-zero code: 1
```

**Comment by jathak** [comment]
The actual error here is coming from attempting to compile a dependency of `node-sass`, which is only being installed because `gulp-sass` declares it as a dev dependency.

If you remove the `--save-dev` from your install script, it should skip installing dev dependencies and allow you to install Dart Sass without issue. Either way, this error isn't actually related to Dart Sass, so I'm closing this issue.
