### ISSUE TITLE
Error: Unsupported operation: 'Uri.base' is not supported

### ISSUE THREAD

**Issue by masx200** [sass/dart-sass#1468]
Error: Unsupported operation: 'Uri.base' is not supported

```
 Error: Unsupported operation: 'Uri.base' is not supported

    at Object._newRenderError (D:\Documents\GitHub\markdown-reader\node_modules\sass\sass.dart.js:13231:19)

    at _render_closure1.call$2 (D:\Documents\GitHub\markdown-reader\node_modules\sass\sass.dart.js:82012:21)

    at _RootZone.runBinary$3$3 (D:\Documents\GitHub\markdown-reader\node_modules\sass\sass.dart.js:27550:18)

    at _FutureListener.handleError$1 (D:\Documents\GitHub\markdown-reader\node_modules\sass\sass.dart.js:26099:19)

    at _Future__propagateToListeners_handleError.call$0 (D:\Documents\GitHub\markdown-reader\node_modules\sass\sass.dart.js:26397:49)

    at Object._Future__propagateToListeners (D:\Documents\GitHub\markdown-reader\node_modules\sass\sass.dart.js:4550:77)

    at _Future._completeError$2 (D:\Documents\GitHub\markdown-reader\node_modules\sass\sass.dart.js:26229:9)

    at _Future__asyncCompleteError_closure.call$0 (D:\Documents\GitHub\markdown-reader\node_modules\sass\sass.dart.js:26325:18)

    at Object._microtaskLoop (D:\Documents\GitHub\markdown-reader\node_modules\sass\sass.dart.js:4606:24)

    at StaticClosure._startMicrotaskLoop (D:\Documents\GitHub\markdown-reader\node_modules\sass\sass.dart.js:4612:11)

```
```css
 @import url(https://unpkg.zhimg.com/bootstrap@5.1.0/dist/css/bootstrap.min.css);
```
"version":"1.35.2"

**Comment by masx200** [comment]
https://github.com/webpack-contrib/sass-loader#problems-with-url
