### ISSUE TITLE
JS API changed or is broken in the latest versions?

### ISSUE THREAD

**Issue by waltercruz** [sass/dart-sass#1605]
with sass < 1.45

`Welcome to Node.js v17.3.1.
Type ".help" for more information.
> const sass = require("sass");
> new sass.types.String('sass');
SassString {
  dartValue: SassString0 {
    text: 'sass',
    hasQuotes: false,
    '_string$__SassString_sassLength': null,
    '_string$_hashCache': null
  }
}`

With sass > 1.45

Welcome to Node.js v17.3.1.
Type ".help" for more information.
> const sass = require("sass");
undefined
> new sass.types.String('sass');
Uncaught Error [ERR_INTERNAL_ASSERTION]: NoSuchMethodError: method not found: 'call'
Receiver: Closure 'JSClassExtension_setCustomInspect_closure'
Arguments: [Instance of 'SassString0', 1, Instance of 'PlainJavaScriptObject', Instance of 'JavaScriptFunction']
    at Object.wrapException (/Users/waltercruz/devel/src/node_modules/sass/sass.dart.js:1241:17)
    at JSClassExtension_setCustomInspect_closure.noSuchMethod$1 (/Users/waltercruz/devel/src/node_modules/sass/sass.dart.js:32056:15)
    at Object.noSuchMethod$1$ (/Users/waltercruz/devel/src/node_modules/sass/sass.dart.js:24396:42)
    at Object.Primitives_functionNoSuchMethod (/Users/waltercruz/devel/src/node_modules/sass/sass.dart.js:1114:16)
    at Object.Primitives__generalApplyFunction (/Users/waltercruz/devel/src/node_modules/sass/sass.dart.js:1167:18)
    at Object.Primitives_applyFunction (/Users/waltercruz/devel/src/node_modules/sass/sass.dart.js:1146:16)
    at Object.Function_apply (/Users/waltercruz/devel/src/node_modules/sass/sass.dart.js:5254:16)
    at _callDartFunctionFastCaptureThis (/Users/waltercruz/devel/src/node_modules/sass/sass.dart.js:22966:16)
    at SassString0.<anonymous> (/Users/waltercruz/devel/src/node_modules/sass/sass.dart.js:22953:18)
    at formatValue (node:internal/util/inspect:780:19)
This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues

running on node v17.3.1 on macOS Catalina

**Comment by voltaek** [comment]
It looks like in Dart Sass release v1.49.1 - the newest version immediately following the version that was the newest available at your time of posting (v1.49.0) - they noted the following in the [changelog](https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#1491):
> Stop supporting non-LTS Node.js versions.

If the issue is actually your use of node v17, then I can only assume that there was something in node v17 that is wholly incompatible with current Dart Sass. If this is the case, this support change appears to be a departure from the (still current) [documentation](https://github.com/sass/dart-sass#nodejs-compatibility), where they list "Current, Active LTS, or Maintenance LTS " as supported releases. As Node v17 is labeled "Current", that is technically included. However, I could see why they wouldn't want to support odd-numbered Node releases, as those are typically more like betas, as they are not recommended for use in production.

Try running the same thing on Node v16 and see if you get the same error. If so, then it's something else, and if not, then we've got our answer. Either way, though, if Dart Sass is no longer supporting "Current" Node releases then its documentation should be updated.

**Comment by Awjin** [comment]
@voltaek That changelog entry probably should have been more specific, but we only dropped support for Node versions that are so old that they fell out of LTS.

Regardless, this does look like a bug with Node 17, potentially related to https://github.com/sass/sass/issues/3250.
