### ISSUE TITLE
@supports with pseudo selector leads to compilation error

### ISSUE THREAD

**Issue by janwidmer** [sass/dart-sass#1656]
Hi There,

I am trying to use the @supports query to check for the pseudo selector `:focus-visible`. The example I am trying to build is described here: https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible#selectively_showing_the_focus_indicator

When I am adding my code to my scss file, I get the following error:

```
SassError: Expected identifier.
   ╷
12 │     @supports (:focus-visible) {
   │                ^
   ╵
  src/patterns/atoms/link/css/link.scss 12:13  root stylesheet
    at node_modules/webpack/lib/NormalModule.js:316:20
    at node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at node_modules/sass-loader/dist/index.js:62:7
    at Function.call$2 (node_modules/sass/sass.dart.js:99051:16)
    at render_closure1.call$2 (node_modules/sass/sass.dart.js:84557:12)
    at _RootZone.runBinary$3$3 (node_modules/sass/sass.dart.js:29579:18)
    at _FutureListener.handleError$1 (node_modules/sass/sass.dart.js:28099:21)
    at _Future__propagateToListeners_handleError.call$0 (node_modules/sass/sass.dart.js:28406:49)
``` 

The code:
```
.a-link {
	&:focus {
		outline: 2px solid #ff0000ff;
	}

	@supports (:focus-visible) {
		&:focus {
			outline: none;
		}
	}

	&:focus-visible {
		background-color: #ffff00ff;
		border-color: #ffff00ff;
		outline: 2px solid #ffff00ff;
	}
}
```

According to the ticket https://github.com/sass/dart-sass/issues/1023 I understand that it should actually work.

My Stack:
- Webpack 4.x
- Sass 1.49.9
- Sass-loader 10.2.1

Am I doing something wrong or is that actually a bug?

**Comment by jathak** [comment]
The correct syntax for this is `@supports selector(:focus-visible)`.

**Comment by janwidmer** [comment]
Thanks for that, seems to work besides phpstorm telling that's an error :)
