### ISSUE TITLE
Missing '}' In an Undefined Area

### ISSUE THREAD

**Issue by ColeyG** [sass/dart-sass#2105]
Running a build gives the following:

```
Error: undefined:1:88: missing '}'
    at error (/var/www/lhsc/web/themes/custom/de_theme/node_modules/css/lib/parse/index.js:62:15)
    at declarations (/var/www/lhsc/web/themes/custom/de_theme/node_modules/css/lib/parse/index.js:259:26)
    at rule (/var/www/lhsc/web/themes/custom/de_theme/node_modules/css/lib/parse/index.js:560:21)
    at rules (/var/www/lhsc/web/themes/custom/de_theme/node_modules/css/lib/parse/index.js:117:70)
    at stylesheet (/var/www/lhsc/web/themes/custom/de_theme/node_modules/css/lib/parse/index.js:81:21)
    at module.exports (/var/www/lhsc/web/themes/custom/de_theme/node_modules/css/lib/parse/index.js:564:20)
    at rework (/var/www/lhsc/web/themes/custom/de_theme/node_modules/rework/index.js:27:21)
    at prependUrls (/var/www/lhsc/web/themes/custom/de_theme/node_modules/gulp-css-url-adjuster/index.js:12:12)
    at Transform._transform (/var/www/lhsc/web/themes/custom/de_theme/node_modules/gulp-css-url-adjuster/index.js:47:15)
    at Transform._read (/var/www/lhsc/web/themes/custom/de_theme/node_modules/gulp-css-url-adjuster/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
```

There are no files that have mismatched curly brackets in my project, I've written a script to check. How might I get a more accurate message from sass other than `undefined:1:88`?

**Comment by nex3** [comment]
This looks like an error that's coming from `node_modules/css`, not from Sass.
