### ISSUE TITLE
The `compressed` output style is sometimes not working

### ISSUE THREAD

**Issue by cedx** [sass/dart-sass#229]
Using `sass` version **1.0.0-beta.5.1** with Dart SDK 1.24.3 (x64) on Ubuntu 17.10:

```dart
import 'dart:async';
import 'dart:io';
import 'package:package_resolver/package_resolver.dart';
import 'package:sass/sass.dart' as sass;

Future writeStylesheet(sass.OutputStyle outputStyle) async {
  var compiled = sass.compile(
    'web/css/main.scss',
    packageResolver: await SyncPackageResolver.current,
    style: outputStyle
  );

  return new File('web/css/main.$outputStyle.css').writeAsString(compiled);
}

Future main() async {
  print('Expanded style...');
  await writeStylesheet(sass.OutputStyle.expanded);
  print('Done.');

  print('Compressed style...');
  await writeStylesheet(sass.OutputStyle.compressed);
  print('Done.');
}
```

Sometimes produces (i.e. it depends on the `main.scss` content):

```shell
$ dart tool/scss.dart 
Expanded style...
Done.
Compressed style...
Unhandled exception:
NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _SerializeVisitor.visitColor (package:sass/src/visitor/serialize.dart:443:16)
#3      SassColor.accept (package:sass/src/value/color.dart:88:51)
#4      _SerializeVisitor._visitValue (package:sass/src/visitor/serialize.dart:430:19)
#5      _SerializeVisitor.visitDeclaration (package:sass/src/visitor/serialize.dart:293:7)
#6      CssDeclaration.accept (package:sass/src/ast/css/declaration.dart:24:49)
#7      _SerializeVisitor._visitChildren.<anonymous closure> (package:sass/src/visitor/serialize.dart:997:15)
#8      _SerializeVisitor._indent (package:sass/src/visitor/serialize.dart:1057:13)
#9      _SerializeVisitor._visitChildren (package:sass/src/visitor/serialize.dart:985:5)
#10     _SerializeVisitor.visitStyleRule (package:sass/src/visitor/serialize.dart:264:5)
#11     CssStyleRule.accept (package:sass/src/ast/css/style_rule.dart:34:49)
#12     _SerializeVisitor.visitStylesheet (package:sass/src/visitor/serialize.dart:141:13)
#13     CssStylesheet.accept (package:sass/src/ast/css/stylesheet.dart:18:49)
#14     serialize (package:sass/src/visitor/serialize.dart:44:8)
#15     compileString (package:sass/src/compile.dart:74:13)
#16     compile (package:sass/src/compile.dart:32:5)
#17     compile (package:sass/sass.dart:53:16)
#18     writeStylesheet (file:///repo/app/tool/scss.dart:7:18)
<asynchronous suspension>
#19     main (file:///repo/app/tool/scss.dart:22:9)
<asynchronous suspension>
#20     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:265)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

The Sass stylesheet is a long list of package imports (all the commented lines are the ones where the `compressed` style breaks):

```sass
// Core.
@import 'package:bootstrap_sass/scss/functions';
@import 'package:app/ui/variables';

// Bootstrap.
@import 'package:bootstrap_sass/scss/variables';
@import 'package:bootstrap_sass/scss/mixins';
//@import 'package:bootstrap_sass/scss/reboot';
//@import 'package:bootstrap_sass/scss/type';
//@import 'package:bootstrap_sass/scss/images';
@import 'package:bootstrap_sass/scss/grid';
//@import 'package:bootstrap_sass/scss/forms';
//@import 'package:bootstrap_sass/scss/buttons';
@import 'package:bootstrap_sass/scss/transitions';
//@import 'package:bootstrap_sass/scss/dropdown';
//@import 'package:bootstrap_sass/scss/nav';
//@import 'package:bootstrap_sass/scss/navbar';
//@import 'package:bootstrap_sass/scss/card';
//@import 'package:bootstrap_sass/scss/alert';
@import 'package:bootstrap_sass/scss/close';
@import 'package:bootstrap_sass/scss/carousel';
//@import 'package:bootstrap_sass/scss/utilities';

// Application.
@import 'package:app/ui/base/scaffolding';
@import 'package:app/ui/base/typography';
//@import 'package:app/ui/base/layout';

// Components.
@import 'package:ng_bootstrap/components/dropdown/dropdown';
@import 'package:app/ui/components/carousel';
@import 'package:app/ui/components/images';
@import 'package:app/ui/components/jumbotron';
//@import 'package:app/ui/components/navbar';
//@import 'package:app/ui/components/spinner';
```

I'm using [`bootstrap_sass` v4.0.0-beta.2](https://pub.dartlang.org/packages/bootstrap_sass/versions/4.0.0-beta.2), and haven't found any clue on which statement breaks the `compressed` style.

**Comment by nex3** [comment]
This was fixed by #228.
