### ISSUE TITLE
Dart sass v1.7.0 CLI not working?

### ISSUE THREAD

**Issue by chrisfromredfin** [sass/dart-sass#380]
I tried to bring dart-sass into my project using Yarn this morning, and use node_modules/.bin/dart-sass to compile as I used to, but I am receiving an error. Below is a full log of the process I went through. I tried using npm instead of Yarn, to the same effect. 

```
~/src
⟩ mkdir test

~/src
⟩ cd test

~/src/test
⟩ yarn init
yarn init v1.7.0
question name (test):
question version (1.0.0):
question description:
question entry point (index.js):
question repository url:
question author:
question license (MIT):
question private:
success Saved package.json
✨  Done in 1.83s.

~/src/test
⟩ yarn add dart-sass
yarn add v1.7.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 124 new dependencies.
info Direct dependencies
└─ dart-sass@1.7.0
info All dependencies
├─ abbrev@1.1.1
├─ ansi-regex@2.1.1
├─ anymatch@2.0.0
├─ aproba@1.2.0
├─ are-we-there-yet@1.1.5
├─ arr-flatten@1.1.0
├─ assign-symbols@1.0.0
├─ async-each@1.0.1
├─ atob@2.1.1
├─ balanced-match@1.0.0
├─ base@0.11.2
├─ binary-extensions@1.11.0
├─ brace-expansion@1.1.11
├─ braces@2.3.2
├─ cache-base@1.0.1
├─ chokidar@2.0.4
├─ chownr@1.0.1
├─ class-utils@0.3.6
├─ code-point-at@1.1.0
├─ collection-visit@1.0.0
├─ concat-map@0.0.1
├─ console-control-strings@1.1.0
├─ copy-descriptor@0.1.1
├─ core-util-is@1.0.2
├─ dart-sass@1.7.0
├─ debug@2.6.9
├─ decode-uri-component@0.2.0
├─ deep-extend@0.6.0
├─ delegates@1.0.0
├─ detect-libc@1.0.3
├─ expand-brackets@2.1.4
├─ extglob@2.0.4
├─ fill-range@4.0.0
├─ for-in@1.0.2
├─ fs-minipass@1.2.5
├─ fs.realpath@1.0.0
├─ fsevents@1.2.4
├─ gauge@2.7.4
├─ get-value@2.0.6
├─ glob-parent@3.1.0
├─ glob@7.1.2
├─ graceful-fs@4.1.11
├─ has-unicode@2.0.1
├─ has-value@1.0.0
├─ has-values@1.0.0
├─ iconv-lite@0.4.23
├─ ignore-walk@3.0.1
├─ inflight@1.0.6
├─ inherits@2.0.3
├─ ini@1.3.5
├─ is-accessor-descriptor@1.0.0
├─ is-binary-path@1.0.1
├─ is-data-descriptor@1.0.0
├─ is-descriptor@1.0.2
├─ is-extglob@2.1.1
├─ is-fullwidth-code-point@1.0.0
├─ is-glob@4.0.0
├─ is-odd@2.0.0
├─ is-plain-object@2.0.4
├─ is-windows@1.0.2
├─ isarray@1.0.0
├─ lodash.debounce@4.0.8
├─ map-visit@1.0.0
├─ micromatch@3.1.10
├─ minimist@0.0.8
├─ minizlib@1.1.0
├─ mixin-deep@1.3.1
├─ mkdirp@0.5.1
├─ ms@2.0.0
├─ nan@2.10.0
├─ nanomatch@1.2.9
├─ needle@2.2.1
├─ node-pre-gyp@0.10.0
├─ nopt@4.0.1
├─ npm-bundled@1.0.3
├─ npm-packlist@1.1.10
├─ npmlog@4.1.2
├─ number-is-nan@1.0.1
├─ object-assign@4.1.1
├─ object-copy@0.1.0
├─ os-homedir@1.0.2
├─ os-tmpdir@1.0.2
├─ osenv@0.1.5
├─ pascalcase@0.1.1
├─ path-dirname@1.0.2
├─ path-is-absolute@1.0.1
├─ posix-character-classes@0.1.1
├─ process-nextick-args@2.0.0
├─ rc@1.2.8
├─ readable-stream@2.3.6
├─ readdirp@2.1.0
├─ remove-trailing-separator@1.1.0
├─ repeat-element@1.1.2
├─ resolve-url@0.2.1
├─ ret@0.1.15
├─ rimraf@2.6.2
├─ safer-buffer@2.1.2
├─ sax@1.2.4
├─ semver@5.5.0
├─ set-blocking@2.0.0
├─ set-immediate-shim@1.0.1
├─ set-value@2.0.0
├─ signal-exit@3.0.2
├─ snapdragon-node@2.1.1
├─ snapdragon-util@3.0.1
├─ source-map-resolve@0.5.2
├─ source-map-url@0.4.0
├─ source-map@0.5.7
├─ split-string@3.1.0
├─ static-extend@0.1.2
├─ string_decoder@1.1.1
├─ string-width@1.0.2
├─ strip-ansi@3.0.1
├─ strip-json-comments@2.0.1
├─ tar@4.4.4
├─ to-regex-range@2.1.1
├─ union-value@1.0.0
├─ unset-value@1.0.0
├─ upath@1.1.0
├─ urix@0.1.0
├─ use@3.1.0
├─ util-deprecate@1.0.2
├─ wide-align@1.1.3
└─ yallist@3.0.2
✨  Done in 4.49s.

~/src/test
⟩ node_modules/.bin/dart-sass --version
/Users/cwells/src/test/node_modules/dart-sass/sass.dart.js:1997
throw H.e(H.cH(a,function(e,f){return e.replace(/[^<,> ]+/g,function(g){return f[g]||g})}(z+y,init.mangledGlobalNames)))},
^

TypeError: Instance of 'dz': type 'dz' is not a subtype of type 'List<String>'
    at Object.e (/Users/cwells/src/test/node_modules/dart-sass/sass.dart.js:1629:3)
    at Object.c (/Users/cwells/src/test/node_modules/dart-sass/sass.dart.js:1997:9)
    at uZ.dart.fh (/Users/cwells/src/test/node_modules/dart-sass/sass.dart.js:10234:19)
    at Object.tK (/Users/cwells/src/test/node_modules/dart-sass/sass.dart.js:1597:69)
    at Object.fy (/Users/cwells/src/test/node_modules/dart-sass/sass.dart.js:5690:28)
    at dart.Cd (/Users/cwells/src/test/node_modules/dart-sass/sass.dart.js:7278:10)
    at Object.run_ (/Users/cwells/src/test/node_modules/dart-sass/sass.dart.js:7266:42)
    at Object.<anonymous> (/Users/cwells/src/test/node_modules/dart-sass/sass.js:8:7)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
```

**Comment by chrisfromredfin** [comment]
I should note that doing `yarn add dart-sass@1.6.2` and issuing the same works fine.

**Comment by Tantawi** [comment]
Same issue here with npm, reverting to sass@1.6.2 fixes the problem.

**Comment by nex3** [comment]
Looks like we accidentally released against the wrong version of Dart. #382 should fix it. Sorry for the trouble.

**Comment by nex3** [comment]
@Delagen How are you installing it?

**Comment by Delagen** [comment]
@nex3  npm update

**Comment by nex3** [comment]
How are you invoking it?

**Comment by Delagen** [comment]
I am using it via api, but error is the same and unreadable, I will note it here when get work.

**Comment by nex3** [comment]
Can you open a new issue with the `render()` call you're using?

**Comment by Delagen** [comment]
I cannot emulate it. Simply use of importer and functions, but when I debug it, no even calls to it.
