### ISSUE TITLE
Error messages for missing files are not verbose

### ISSUE THREAD

**Issue by alex-page** [sass/dart-sass#406]
I recently had an issue with a missing file in my sass bundle. The error message provided by `dart-sass` made it very hard to debug.
```
undefined:3
throw error;
^

Error: Instance of 'ht'
    at Object.iJ (/Users/alexpage/Sites/dta/uikit/node_modules/sass/sass.dart.js:11638:32)
    at tB.dart.BS (/Users/alexpage/Sites/dta/uikit/node_modules/sass/sass.dart.js:11529:5)
    at Object.rp (/Users/alexpage/Sites/dta/uikit/node_modules/sass/sass.dart.js:1544:69)
    at Object.eg (/Users/alexpage/Sites/dta/uikit/node_modules/sass/sass.dart.js:5191:28)
    at dart.AN (/Users/alexpage/Sites/dta/uikit/node_modules/sass/sass.dart.js:6733:28)
    at Object.renderSync (/Users/alexpage/Sites/dta/uikit/node_modules/sass/sass.dart.js:6722:42)
    at Sassify (/Users/alexpage/Sites/dta/uikit/scripts/helper.js:177:24)
    at Object.sass (/Users/alexpage/Sites/dta/uikit/scripts/helper.js:567:5)
    at Object.init (/Users/alexpage/Sites/dta/uikit/scripts/helper.js:553:19)
    at Object.HELPER.init (/Users/alexpage/Sites/dta/uikit/scripts/helper.js:1221:18)
```

Using `node-sass` I get a very descriptive error message when an included file is not existant:
```
Error: File to read not found or unreadable: /Users/alexpage/Sites/dta/uikit/packages/side-nav/tests/jquery/test.scss
```

I recently started experimenting with `dart-sass` I would like to do a PR to fix this though I am not sure where to start.

**Comment by nex3** [comment]
What version of Sass are you using? How are you invoking it? Are you missing an entrypoint file, or one that's being imported?

**Comment by alex-page** [comment]
Hey @nex3 thanks for the response.

I am using the npm package `sass` version 1.5.1 which I now realise is not the latest.

We run it in a node js file like so:
```
Sass.renderSync({
	file: scss,
	indentType: 'tab',
	precision: 8,
	includePaths: [ './lib/sass/' ],
	outputStyle: 'compressed',
})
```

In the node js file we run a function wrapping that code for a specific file. There was a bug where the file did not exist and the function was being ran ( entry point file ).

Let me know if you need any more information. I will update my version of `sass` now as well.

**Comment by alex-page** [comment]
Thankyou 👍
